---
title: "EDA-unemployment"
author: "Albert Sun"
date: "10/31/2020"
output: html_document
---

```{r, include=FALSE}
library(tidyverse)
library(tidyselect)
library(here)
library(janitor)
library(lubridate)
library(hrbrthemes)
```


```{r read data}
mobility <- read.csv(here("data","unemployment-data.csv")) %>%
  clean_names %>%
  select(-i_laus_code) %>%
  mutate(state = str_sub(county_name_state_abbreviation, -2, -1)) %>%
  mutate(county = str_sub(county_name_state_abbreviation, 0, -5)) %>%
  mutate(month = str_sub(period, 0, 3)) %>%
  mutate(year = str_sub(period, -2, -1)) %>%
  select(-county_name_state_abbreviation)

mobility

```

```{r find average unemployment}
feb_mobility <- mobility %>%
  filter(year == 20, month != "Jan") %>%
  mutate(unemployment_rate = as.numeric(unemployment_rate)) %>%
  filter(month == "Feb") 

aug_mobility <- mobility %>%
  filter(year == 20, month != "Jan") %>%
  mutate(unemployment_rate = as.numeric(unemployment_rate)) %>%
  filter(month == "Aug") 

change_feb_aug <- feb_mobility %>%
  inner_join(aug_mobility, by = "county") %>%
  select(county, state.x, unemployment_rate.x, unemployment_rate.y) %>%
  mutate(unemployment_change = unemployment_rate.y - unemployment_rate.x) %>%
  select(-unemployment_rate.x, -unemployment_rate.y) %>%
  distinct(county, .keep_all= TRUE) 

change_feb_aug
```

```{r unemployment time plot}
mobility <- mobility %>%
  slice(1:45066)

mobility <- mobility %>%
  filter(year == 20) %>%
  mutate(unemployed = as.numeric(gsub(",", "", unemployed))) %>%
  mutate(labor_force = as.numeric(gsub(",", "", labor_force)))

mobility2 <- mobility %>%
  select(labor_force, unemployed, month) %>%
  na.omit()

totals <- mobility2 %>%
  group_by(month) %>%
  summarise(labor = sum(labor_force),
            unemployed = sum(unemployed)) %>%
  mutate(pct = unemployed / labor * 100)
  
months <- c("Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug")

totals <- totals %>%
  mutate(month =  factor(month, levels = months)) %>%
  arrange(month) %>%
  slice(1:7)
```


```{r}
ggplot(data = totals, aes(x = month, y = pct, group = 1)) +
       geom_line(color = "navy") +
  geom_point() +
  labs(x = "Month", y = "Unemployment Rate", title = "Slow Economic Recovery Since the Spring") +
  theme_ipsum_rc()
```


```{r}
write_csv(change_feb_aug, file = here("data","unemployment-change.csv"))

```

