---
title: "Google Movement Data Analysis"
author: "Albert Sun, Lily Zhu"
output: 
    pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load packages}
library(tidyverse)
library(lubridate)
library(ggplot2)
library(dygraphs)
library(plotly)
#library(hrbrthemes)
```

```{r read data}
mobility <- read.csv("../data/US-Mobility-Report.csv")
```

```{r date num}
mobility <- mobility %>% 
  mutate(date_num = as.Date(date))
```

```{r}
ggplot(data = mobility, mapping = aes(x = retail_and_recreation_percent_change_from_baseline)) +
  geom_bar()

ggplot(data = mobility, mapping = aes(x = grocery_and_pharmacy_percent_change_from_baseline)) +
  geom_bar()

ggplot(data = mobility, mapping = aes(x = parks_percent_change_from_baseline)) +
  geom_bar()

ggplot(data = mobility, mapping = aes(x = transit_stations_percent_change_from_baseline)) +
  geom_bar()

ggplot(data = mobility, mapping = aes(x = workplaces_percent_change_from_baseline)) +
  geom_bar()

ggplot(data = mobility, mapping = aes(x = residential_percent_change_from_baseline)) +
  geom_bar()
```

```{r}
mobility %>% 
  filter(!is.na(retail_and_recreation_percent_change_from_baseline)) %>% 
  summarise(mean = mean(retail_and_recreation_percent_change_from_baseline),
          median = median(retail_and_recreation_percent_change_from_baseline),
          sd = sd(retail_and_recreation_percent_change_from_baseline),
          iqr = IQR(retail_and_recreation_percent_change_from_baseline),
          min = min(retail_and_recreation_percent_change_from_baseline),
          max = max(retail_and_recreation_percent_change_from_baseline))
```

```{r}
mobility %>% 
  filter(!is.na(grocery_and_pharmacy_percent_change_from_baseline)) %>% 
  summarise(mean = mean(grocery_and_pharmacy_percent_change_from_baseline),
          median = median(grocery_and_pharmacy_percent_change_from_baseline),
          sd = sd(grocery_and_pharmacy_percent_change_from_baseline),
          iqr = IQR(grocery_and_pharmacy_percent_change_from_baseline),
          min = min(grocery_and_pharmacy_percent_change_from_baseline),
          max = max(grocery_and_pharmacy_percent_change_from_baseline))
```

```{r}
mobility %>% 
  filter(!is.na(parks_percent_change_from_baseline)) %>% 
  summarise(mean = mean(parks_percent_change_from_baseline),
          median = median(parks_percent_change_from_baseline),
          sd = sd(parks_percent_change_from_baseline),
          iqr = IQR(parks_percent_change_from_baseline),
          min = min(parks_percent_change_from_baseline),
          max = max(parks_percent_change_from_baseline))
```

```{r}
mobility %>% 
  filter(!is.na(transit_stations_percent_change_from_baseline)) %>% 
  summarise(mean = mean(transit_stations_percent_change_from_baseline),
          median = median(transit_stations_percent_change_from_baseline),
          sd = sd(transit_stations_percent_change_from_baseline),
          iqr = IQR(transit_stations_percent_change_from_baseline),
          min = min(transit_stations_percent_change_from_baseline),
          max = max(transit_stations_percent_change_from_baseline))
```

```{r}
mobility %>% 
  filter(!is.na(workplaces_percent_change_from_baseline)) %>% 
  summarise(mean = mean(workplaces_percent_change_from_baseline),
          median = median(workplaces_percent_change_from_baseline),
          sd = sd(workplaces_percent_change_from_baseline),
          iqr = IQR(workplaces_percent_change_from_baseline),
          min = min(workplaces_percent_change_from_baseline),
          max = max(workplaces_percent_change_from_baseline))
```

```{r}
mobility %>% 
  filter(!is.na(residential_percent_change_from_baseline)) %>% 
  summarise(mean = mean(residential_percent_change_from_baseline),
          median = median(residential_percent_change_from_baseline),
          sd = sd(residential_percent_change_from_baseline),
          iqr = IQR(residential_percent_change_from_baseline),
          min = min(residential_percent_change_from_baseline),
          max = max(residential_percent_change_from_baseline))
```

```{r ny}
ny_feb <- mobility %>%
  filter(sub_region_1 == "New York", date_num >= as.Date("2020-02-15"), date_num < as.Date("2020-03-01"))
```

```{r ny eda}
ny_feb %>%
  ggplot(aes(x = date, y = retail_and_recreation_percent_change_from_baseline)) +
  geom_point() + 
  labs(x = "Date", y = "Retail and recreation (% change from baseline)") +
  theme(axis.text.x = element_text(angle = 90))

ny_feb %>%
  ggplot(aes(x = date, y = grocery_and_pharmacy_percent_change_from_baseline)) +
  geom_point() +
   labs(x = "Date", y = "Grocery and pharmacy (% change from baseline)") +
  theme(axis.text.x = element_text(angle = 90))

ny_feb %>%
  ggplot(aes(x = date, y = parks_percent_change_from_baseline)) +
  geom_point() +
   labs(x = "Date", y = "Parks (% change from baseline)") +
  theme(axis.text.x = element_text(angle = 90))

ny_feb %>%
  ggplot(aes(x = date, y = transit_stations_percent_change_from_baseline)) +
  geom_point() +
   labs(x = "Date", y = "Transit stations(% change from baseline)") +
  theme(axis.text.x = element_text(angle = 90))

ny_feb %>%
  ggplot(aes(x = date, y = workplaces_percent_change_from_baseline)) +
  geom_point() +
   labs(x = "Date", y = "Workplaces (% change from baseline)") +
  theme(axis.text.x = element_text(angle = 90))

ny_feb %>%
  ggplot(aes(x = date, y = residential_percent_change_from_baseline)) +
  geom_point() +
   labs(x = "Date", y = "Residential (% change from baseline)") +
  theme(axis.text.x = element_text(angle = 90))
```

```{r durham eda, eval = FALSE}
durham <- mobility %>%
  filter(sub_region_2 == "Durham County")

durham %>%
  head(50) %>%
  ggplot(aes(x = date, y = workplaces_percent_change_from_baseline)) +
  geom_point() #+
  #theme_ipsum_rc() 
```

```{r}
nc_avg <- mobility %>%
  filter(sub_region_1 == "North Carolina") %>%
  group_by(sub_region_2, na.rm=TRUE) %>%
  summarise(retail_avg = mean(retail_and_recreation_percent_change_from_baseline, na.rm=TRUE),
            grocery_avg = mean(grocery_and_pharmacy_percent_change_from_baseline, na.rm=TRUE),
            parks_avg = mean(parks_percent_change_from_baseline, na.rm=TRUE),
            transit_avg = mean(transit_stations_percent_change_from_baseline, na.rm=TRUE),
            workplaces_avg = mean(workplaces_percent_change_from_baseline, na.rm=TRUE),
            residential_avg = mean(residential_percent_change_from_baseline, na.rm=TRUE))
nc_avg

```



```{r plot}
#test_plot <- ggplot(mtcars, aes(mpg, wt)) +
  #geom_point() +
  #labs(x="Fuel efficiency (mpg)", y="Weight (tons)",
       #title="Seminal ggplot2 scatterplot example",
       #subtitle="A plot that is only useful for demonstration purposes",
       #caption="Brought to you by the letter 'g'") +
  #theme_ipsum_rc()
```

```{r save file}
#ggsave("../output/test-plot.png", test_plot, units = "in", width = 850/100, height = 600/100 )
```

# EDA 


# Linear Regression Code

